apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - workload.yaml
  - prometheus.yaml
  - opentelemetry.yaml
  - grafana.yaml
  - control-plane.yaml
  - frontend.yaml
